(function(g){var window=this;'use strict';var R3=function(a){a.ra("cardstatechange",a.Gk()&&a.So()?1:0)},S3=function(a,b){var c=g.Wa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},pib=function(a){var b=g.Kr(a);
a=g.Nr(a);return new g.zr(b.x,b.y,a.width,a.height)},qib=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.XC(a,b,function(){g.YC(e);c.apply(a,arguments)},d)},V3=function(a){a=g.ab(a);
delete T3[a];g.jd(T3)&&U3&&U3.stop()},sib=function(){U3||(U3=new g.eu(function(){rib()},20));
var a=U3;a.isActive()||a.start()},rib=function(){var a=g.eb();
g.Tc(T3,function(b){tib(b,a)});
g.jd(T3)||sib()},W3=function(a,b,c,d){g.Cu.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.S=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},tib=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;uib(a,a.progress);1==a.progress?(a.j=0,V3(a),a.onFinish(),a.jr()):a.isPlaying()&&a.HK()},uib=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.S[c]-a.B[c])*b+a.B[c]},vib=function(a,b){g.xb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},X3=function(a,b,c,d,e){W3.call(this,b,c,d,e);
this.element=a},wib=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
X3.call(this,a,b,c,d,e)},xib=function(a){return Math.pow(a,3)},yib=function(a){return 3*a*a-2*a*a*a},zib=function(a){g.J.call(this);
this.B=a||window;this.j=[]},Y3=function(a){return a.baseUrl||null},Z3=function(a,b){return g.xs(g.bq(a,b),function(c){return!!c})},Aib=function(a,b,c){function d(oa){var ia=oa.hovercardButton;
if(!ia)return null;ia=ia.subscribeButtonRenderer;if(!ia)return null;var Aa=f(ia.unsubscribedButtonText),X=f(ia.subscribedButtonText);if(ia.subscribed){var wa=f(ia.subscriberCountWithUnsubscribeText);var ca=f(ia.subscriberCountText)}else wa=f(ia.subscriberCountText),ca=f(ia.subscriberCountWithSubscribeText);var Ra=null;if(oa.signinEndpoint){Ra=S3(oa,"signinEndpoint","webNavigationEndpointData","url");if(!Ra){var y,V;Ra=null==(V=g.S(null==(y=ia.signInEndpoint)?void 0:y.commandMetadata,g.J2))?void 0:
V.url}if(!Ra)return null}return Aa&&(X||Ra)?{subscribed:ia.subscribed,subscribeText:Aa,subscribeCount:wa,unsubscribeText:X,unsubscribeCount:ca,enabled:ia.enabled,signinUrl:Ra,classic:oa.useClassicSubscribeButton}:null}
function e(oa){if(oa){var ia=[],Aa=oa.videoId;Aa&&ia.push("v="+Aa);(Aa=oa.playlistId)&&ia.push("list="+Aa);(oa=oa.startTimeSeconds)&&ia.push("t="+oa);return"/watch?"+ia.join("&")}}
function f(oa){if(!oa)return null;var ia=oa.simpleText;return ia?ia:oa.runs?g.bq(oa.runs,function(Aa){return Aa.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,x=!1,B=null,G=null,F=null,I=null,P=null,R=null;if("VIDEO"===h)g.S(l,g.IG)?m=g.S(l,g.IG).url:(R=g.S(l,g.sT),m=e(R)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.S(l,g.IG)?m=g.S(l,g.IG).url:(R=g.S(l,g.sT),m=e(R)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=S3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;q="new";(x=!!b.isSubscribe)?B=d(b):G=f(b.subscribersText)}else"WEBSITE"===h?((F=S3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(P=f(b.additionalFeesText)),(n=S3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=S3(b,"title","accessibility","accessibilityData","label");var Y=b.endpoint?b.endpoint.clickTrackingParams:null,
ka="";if(b.metadata){var ra=f(b.metadata);ra&&(ka=ra)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ka,callToAction:f(b.callToAction),mV:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,ED:p,playlistLength:t,channelId:v,subscribeButton:B,subscribersText:G,isSubscribe:x,Au:m||null,g6:n,sessionData:Y?{itct:Y}:null,aaa:q,gC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:Z3(b.impressionUrls||[],Y3),T5:Z3(b.hovercardShowUrls||[],Y3),clickUrls:Z3(l.loggingUrls||[],Y3),visualElement:g.OF(b.trackingParams),productPrice:I,additionalFeesText:P,watchEndpoint:R||null}},Bib=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:Z3(a.impressionUrls||[],Y3),elements:Z3(a.elements||[],function(d,e){return Aib(b,d,e)})};
a.trackingParams&&(c.visualElement=g.OF(a.trackingParams));return c},Cib=function(a){g.yV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.S=[];this.ea=!0;this.K=0;a=a.W();this.ma=g.jS(a)||g.lS(a);this.events=new g.ZK(this);g.L(this,this.events);this.events.V(this.player,g.pK("creatorendscreen"),this.onCueRangeEnter);this.events.V(this.player,g.qK("creatorendscreen"),this.onCueRangeExit);this.events.V(this.player,"resize",this.Nb);this.events.V(window,"focus",this.E9);this.load();var b=g.lf("STYLE");(g.Xe("HEAD")[0]||document.body).appendChild(b);g.ub(this,function(){g.yf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Dib=function(a){return a.player.getVideoData().Td?"current":a.ma?"new":"current"},$3=function(a){return"creator-endscreen-editor"===a.player.W().playerStyle},Eib=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Bib(f,Dib(a))));a4(a,f)},
urlParams:{v:c},withCredentials:!0};a.ma&&(c.urlParams.ptype="embedded");var d=b.Ux;d&&(c.postParams={ad_tracking:d});if(b=g.kRa(b))if(b=g.Hn(b),b=g.ae(b))a.C=g.oC(b,c)},a4=function(a,b,c){c=void 0===c?!0:c;
a.player.mf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.S.length&&(a.S.forEach(function(l){l.dispose()}),a.S.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Fib(a);c=[];d=new g.oK(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.W().B||(a.B=new g.T({I:"div",T:"ytp-ce-shadow"}),g.wU(a.player,a.B.element,4),a.D=new g.VG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Gib(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.wU(a.player,f.element,4);var h=new g.oK(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Hib(a,f,e)}else g.UF(new g.nD("buildEndscreenElement null",
e))}a.player.xf(c);a.Nb()}},Fib=function(a){var b=g.PF(),c=g.QF();
c&&b&&a.endscreen.visualElement&&g.WB(g.$F)(void 0,c,b,a.endscreen.visualElement)},Gib=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Na:["ytp-ce-element","ytp-ce-video"],Y:{tabindex:"0","aria-label":b.gC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-covering-image",Y:b4(b)},{I:"div",T:"ytp-ce-covering-shadow-top"},{I:"a",T:"ytp-ce-covering-overlay",Y:{href:c4(a,b.Au),tabindex:"-1"},X:[{I:"div",Na:["ytp-ce-video-title","ytp-webkit-ellipsis"],Y:{dir:g.Gu(b.title||"")},Aa:b.title},{I:"div",T:b.ED?"ytp-ce-live-video-duration":"ytp-ce-video-duration",Aa:b.videoDuration||
void 0}]}]};c=new g.T(a);break;case "PLAYLIST":a={I:"div",Na:["ytp-ce-element","ytp-ce-playlist"],Y:{tabindex:"0","aria-label":b.gC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-covering-image",Y:b4(b)},{I:"div",T:"ytp-ce-covering-shadow-top"},{I:"a",T:"ytp-ce-covering-overlay",Y:{href:c4(a,b.Au),tabindex:"-1"},X:[{I:"div",Na:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],Y:{dir:g.Gu(b.title||"")},Aa:b.title},{I:"div",T:"ytp-ce-playlist-count",X:[{I:"div",T:"ytp-ce-playlist-icon"},
{I:"div",T:"ytp-ce-playlist-count-text",Aa:b.playlistLength||void 0}]}]}]};c=new g.T(a);break;case "CHANNEL":c={I:"div",Na:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],Y:{tabindex:"0","aria-label":b.gC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-expanding-overlay",X:[{I:"div",T:"ytp-ce-expanding-overlay-hider"},{I:"div",T:"ytp-ce-expanding-overlay-background"},{I:"div",T:"ytp-ce-expanding-overlay-content",X:[{I:"div",
T:"ytp-ce-expanding-overlay-body",X:[{I:"div",T:"ytp-ce-expanding-overlay-body-padding",X:[{I:"a",Na:["ytp-ce-channel-title","ytp-ce-link"],Y:{href:c4(a,b.Au),target:"_blank",tabindex:"-1",dir:g.Gu(b.title||"")},Aa:b.title},b.subscribeButton?{I:"div",T:"ytp-ce-subscribe-container",X:[{I:"div",T:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",T:"ytp-ce-channel-subscribers-text",Aa:b.subscribersText}:"",b.metadata?{I:"div",Na:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
Aa:b.metadata}:""]}]}]}]},{I:"div",T:"ytp-ce-expanding-image",Y:b4(b)}]};c=new g.T(c);var d=g.Ye(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.mu(d,"ytp-ce-subscribe-button");if(a.player.W().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.kW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.S.push(e)}break;case "WEBSITE":a={I:"div",Na:["ytp-ce-element","ytp-ce-website"],Y:{tabindex:"0","aria-label":b.gC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-expanding-overlay",X:[{I:"div",T:"ytp-ce-expanding-overlay-hider"},{I:"div",T:"ytp-ce-expanding-overlay-background"},{I:"div",T:"ytp-ce-expanding-overlay-content",X:[{I:"div",T:"ytp-ce-expanding-overlay-body",X:[{I:"div",
T:"ytp-ce-expanding-overlay-body-padding",X:[{I:"div",T:"ytp-ce-website-title",Y:{dir:g.Gu(b.title||"")},Aa:b.title},{I:"div",T:"ytp-ce-website-metadata",Aa:b.metadata},{I:"a",Na:["ytp-ce-website-goto","ytp-ce-link"],Y:{href:c4(a,b.Au),target:"_blank",tabindex:"-1"},Aa:b.callToAction}]}]}]}]},{I:"div",T:"ytp-ce-expanding-image",Y:b4(b)},{I:"div",T:"ytp-ce-expanding-icon",Y:Iib(b.iconUrl)}]};c=new g.T(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",T:"ytp-ce-merchandise-price-container",
X:[{I:"div",T:"ytp-ce-merchandise-price",Aa:b.productPrice}]},b.additionalFeesText&&c.X.push({I:"div",T:"ytp-ce-merchandise-additional-fees",Aa:b.additionalFeesText})),a={I:"div",Na:["ytp-ce-element","ytp-ce-merchandise"],Y:{tabindex:"0","aria-label":b.gC||"","aria-hidden":"true"},X:[{I:"div",T:"ytp-ce-element-shadow"},{I:"div",T:"ytp-ce-expanding-overlay",X:[{I:"div",T:"ytp-ce-expanding-overlay-hider"},{I:"div",T:"ytp-ce-expanding-overlay-background"},{I:"div",T:"ytp-ce-expanding-overlay-content",
X:[{I:"div",T:"ytp-ce-expanding-overlay-body",X:[{I:"div",T:"ytp-ce-expanding-overlay-body-padding",X:[{I:"div",T:"ytp-ce-merchandise-title",Y:{dir:g.Gu(b.title||"")},Aa:b.title},c,{I:"div",T:"ytp-ce-merchandise-metadata",Aa:b.metadata},{I:"a",Na:["ytp-ce-merchandise-goto","ytp-ce-link"],Y:{href:c4(a,b.Au),target:"_blank",tabindex:"-1"},Aa:b.callToAction}]}]}]}]},{I:"div",T:"ytp-ce-expanding-image",Y:b4(b)},{I:"div",T:"ytp-ce-merchandise-invideo-cta-container",X:[{I:"div",T:"ytp-ce-merchandise-invideo-cta",
Aa:b.callToAction||void 0}]}]},c=new g.T(a)}b.isPlaceholder&&g.mu(c.element,"ytp-ce-placeholder");return c},b4=function(a){if(a.mV)var b=a.mV.thumbnails;
return Iib(b?b[b.length-1].url:null)},Iib=function(a){return a?{style:"background-image: url("+a+")"}:{}},Hib=function(a,b,c){function d(m){m&&(b.Ua("blur",function(){"none"!=m.style.display&&a.ea&&m.focus()}),b.V(m,"focus",f),b.V(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.mu(b.element,"ytp-ce-force-expand"),d4(a,c.id,!0)):(g.ou(b.element,"ytp-ce-force-expand"),g.ou(b.element,"ytp-ce-element-hover"),d4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ua("mouseenter",function(){Jib(a,b,c)});
b.Ua("mouseleave",function(){Kib(a,b,c)});
a.player.W().B||b.Ua("click",function(){g.mu(b.element,"ytp-ce-element-hover")});
b.Ua("click",function(m){Lib(a,c,m)});
b.Ua("keypress",function(m){Lib(a,c,m)});
b.Ua("focus",function(){Jib(a,b,c)});
b.Ua("blur",function(){Kib(a,b,c)});
b.Ua("touchstart",function(){Jib(a,b,c)});
var l=g.$e("ytp-ce-expanding-overlay-hider",b.element);l&&b.V(l,"touchstart",function(m){m.stopPropagation();g.ou(b.element,"ytp-ce-element-hover");g.ou(b.element,"ytp-ce-force-expand")});
b.Ua("keydown",function(m){a.ea=9===m.keyCode&&!m.shiftKey});
d(g.$e("ytp-sb-subscribe",b.element));d(g.$e("ytp-sb-unsubscribe",b.element));b.Ua("focus",f);b.Ua("blur",h)},Lib=function(a,b,c){if(b.Au&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.lu(d,"ytp-ce-element");){g.lu(d,"subscribe-label")&&Mib(a,b);
if(g.lu(d,"ytp-ce-channel-subscribe"))return;d=g.zf(d)}if(!d||g.lu(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Kib(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.aaa)Mib(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Hn(c4(a,b.Au)),g.uH(g.ae(c),void 0,b.sessionData);else{var e=g.vS(a.player.W())||a.player.getVideoData().Td,f=function(){var h=c4(a,b.Au),l=b.sessionData,m=b.watchEndpoint,n=g.bC(h);e&&n&&(n.v||n.list)?a.player.Bo(n.v,
l,n.list,!1,void 0,m||void 0):g.Pva(h,l)};
Mib(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},c4=function(a,b){a=a.player.W();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.CS(a)+b}else return"";return b},Jib=function(a,b,c){g.lu(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.mu(b.element,"ytp-ce-element-hover"):a.player.W().B?(new g.eu(function(){g.mu(b.element,"ytp-ce-element-hover")},200)).start():g.mu(b.element,"ytp-ce-element-hover"),e4(a,c.T5),d4(a,c.id,!0))},Kib=function(a,b,c){g.ou(b.element,"ytp-ce-element-hover");
g.ou(b.element,"ytp-ce-force-expand");d4(a,c.id,!1)},d4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.qu(a.j[e].element,"ytp-ce-element-shadow-show",c)},e4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||$3(a))c&&c();else{b=Nib(a,b);var e=0,f=!1,h=new g.eu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.EE(b[a],d)}},Mib=function(a,b,c){e4(a,b.clickUrls,c);
(a=g.QF())&&b.g6&&g.gG(a,b.visualElement)},Nib=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Oib(b[d],c));return a},Oib=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Pib=function(a){return"string"===typeof a?a:""},f4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Qib=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},g4=function(a){return a.value?a.value:null},h4=function(a){if(!a)return null;
var b=g.Hn(Pib(a.value));b=g.ae(b);if(!b)return null;var c=f4(a.target,Rib,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Qib(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Sib=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Vib=function(a){if(!a)return null;
var b=f4(a.type,Tib),c=f4(a.trigger,Uib);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=h4(a?a:null);return b?new Sib(b,c,a):null},Wib=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Xib=function(a,b){return g.Bb(a.action,b)},Yib=function(a,b){this.context=a;
this.j=b},Zib=function(a){return a.customMessage?i4("div","iv-card-message",a.customMessage):""},j4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",T:"iv-card-image",Y:{style:a},X:c}},$ib=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(i4("li","",c.value));return{I:"ul",T:"iv-card-meta-info",X:b}},i4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Gu(c);return{I:a,Y:b,Aa:c}},ajb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.qC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.qC+");");c.dir=g.Gu(a.customMessage);var d=[{I:"span",Aa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",T:"iv-card-link-icon"}));return{I:"div",Na:b,Y:c,X:d}},k4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.bj.click,5)}},bjb=function(a,b){this.merchant=a;
this.price=b},cjb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},djb=function(a,b){return b?b:cjb(a)?"current":"new"},l4=function(a,b){g.J.call(this);
var c=this;this.element=a;this.context=b;this.xb=!1;this.eb=new Map;this.fb=new Map;this.context.J.addEventListener(g.pK("annotations_module"),function(d){(d=c.eb.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.qK("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)})},m4=function(a,b,c,d,e,f,h){a.context.j.Ua(b,"click",function(l){a.IK(c,d,e,f||[],h||0,l)});
a.context.j.Ua(b,"touchstart",function(){a.xb=!1});
a.context.j.Ua(b,"touchmove",function(){a.xb=!0})},ejb=function(a){var b;
return(null==(b=g.S(a,g.IG))?0:b.url)?g.S(a,g.IG).url:(a=g.S(a,g.sT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},n4=function(a,b,c){return{JW:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
WZ:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
iK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},fjb=function(a,b,c){l4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Pa=this.Mb=this.C=this.isInitialized=!1;this.cards=[];this.Cb=this.ma=this.Oa=this.G=this.Ya=this.j=null;this.qa=[];this.va=this.S=this.vg=this.Ia=null;this.K=0;this.Fa=new g.eu(function(){},c.Z.Pi?4E3:3E3);
g.L(this,this.Fa);this.rb=new g.eu(function(){});
g.L(this,this.rb);this.Ca=new Yib(c,function(e,f,h,l,m,n){m4(d,e,f,h,l,m,n)});
this.ea=new g.T({I:"div",T:"iv-drawer",Y:{id:"iv-drawer"},X:[{I:"div",T:"iv-drawer-header",Y:{"aria-role":"heading"},X:[{I:"span",T:"iv-drawer-header-text"},{I:"button",Na:["iv-drawer-close-button","ytp-button"],Y:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",T:"iv-drawer-content"}]});g.L(this,this.ea);this.D=this.ea.element;this.kb=new g.VG(this.ea,330);g.L(this,this.kb);this.Ub=g.$e("iv-drawer-header-text",this.D);this.B=g.$e("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Mb&&o4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Mb=d.C)&&p4(d)});
this.Va=new g.ZK(this);g.L(this,this.Va);this.J.addEventListener("videodatachange",this.ut.bind(this))},gjb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){o4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){p4(a)});
var c=b.headerText;g.Bf(a.Ub,c);a.ma&&a.ma.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ia=g.OF(b.trackingParams);a.S=g.OF(b.closeTrackingParams);a.vg=g.OF(b.iconTrackingParams)},hjb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.W().experiments.ob("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.wG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,bj:{},To:null,Cl:e.trackingParams?g.OF(e.trackingParams):null,vg:f&&f.trackingParams?g.OF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
qC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};q4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.wG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:r4(a,c,b,f),sponsored:!1,bj:n4(f,e,f.command),To:f.trackingParams?g.OF(f.trackingParams):null,Cl:e.trackingParams?g.OF(e.trackingParams):null,vg:l&&l.trackingParams?g.OF(l.trackingParams):null,imageUrl:s4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.wG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,qC:null,title:f.title?g.wG(f.title):"",customMessage:f.callToAction?g.wG(f.callToAction):"",url:g.S(f.command,g.IG).url?h4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(f.command,g.IG).url}):null,onClickCommand:null};q4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.wG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:r4(a,c,b,e),sponsored:!1,bj:n4(e,f,e.endpoint),To:e.trackingParams?g.OF(e.trackingParams):null,Cl:f.trackingParams?g.OF(f.trackingParams):null,vg:l&&l.trackingParams?g.OF(l.trackingParams):null,channelId:g.S(e.endpoint,g.VU).browseId,customMessage:e.customText?g.wG(e.customText):null,UY:s4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.wG(e.channelName):"",metaInfo:[e.subscriberCountText?g.wG(e.subscriberCountText):""],url:h4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(e.endpoint,g.VU).canonicalBaseUrl?g.S(e.endpoint,g.VU).canonicalBaseUrl:"/channel/"+g.S(e.endpoint,g.VU).browseId}),onClickCommand:null};q4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.wG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:r4(a,c,b,e),sponsored:!1,bj:n4(e,f,e.action),To:e.trackingParams?g.OF(e.trackingParams):null,Cl:f.trackingParams?g.OF(f.trackingParams):null,vg:l&&l.trackingParams?g.OF(l.trackingParams):null,BF:s4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.wG(e.customMessage):null,playlistVideoCount:g.wG(e.playlistVideoCount),title:e.playlistTitle?g.wG(e.playlistTitle):"",metaInfo:[e.channelName?g.wG(e.channelName):
"",e.videoCountText?g.wG(e.videoCountText):""],url:h4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ejb(e.action)}),onClickCommand:null};q4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.wG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:r4(a,c,b,e),sponsored:!1,bj:n4(e,f,e.action),To:e.trackingParams?g.OF(e.trackingParams):null,Cl:f.trackingParams?g.OF(f.trackingParams):null,vg:l&&l.trackingParams?g.OF(l.trackingParams):null,BF:s4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.wG(e.lengthString):null,customMessage:e.customMessage?g.wG(e.customMessage):null,title:e.videoTitle?g.wG(e.videoTitle):"",metaInfo:[e.channelName?g.wG(e.channelName):
"",e.viewCountText?g.wG(e.viewCountText):""],isLiveNow:!!e.badge,url:h4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:ejb(e.action)}),onClickCommand:null};q4(a,b)}}}}}a.K++},s4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},r4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},jjb=function(a,b){if(b=ijb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.og.id),g.yf(b.jM),g.Fb(a.cards,b),a.xG(),t4(a)},o4=function(a,b,c){if(!a.C){a.kb.show();
a.Ya=new g.eu(function(){g.mu(a.context.J.getRootNode(),g.aZ.IV_DRAWER_OPEN)},0);
a.Ya.start();a.Va.V(a.B,"mousewheel",function(h){a.Fa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.QF();d&&a.Ia&&a.S&&g.eG(d,[a.Ia,a.S]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.sX||(f.sX=!0,kjb(a.context.logger,f.og.bj.JW,b)),d&&g.eG(d,[f.og.To]);R3(a.J);c&&(a.G=new g.eu(function(){a.Oa=a.ma;a.Cb.focus()},330),a.G.start())}},p4=function(a){a.C&&(a.kb.hide(),g.cD(a.Va),g.ou(a.context.J.getRootNode(),g.aZ.IV_DRAWER_OPEN),a.C=!1,R3(a.J),a.G&&a.G.stop(),a.G=new g.eu(function(){a.Oa&&(a.Oa.focus(),a.Oa=null)},330),a.G.start())},mjb=function(a){g.nu(a.Gb(),
[g.aZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.wU(a.J,a.D,5);ljb(a);a.ma=g.$e("ytp-cards-button",a.J.getRootNode());a.Cb=g.$e("iv-drawer-close-button",a.D);a.isInitialized=!0},ljb=function(a){var b=g.$e("iv-drawer-close-button",a.D);
a.context.j.Ua(b,"click",a.Y3,a);a.context.j.Ua(a.B,"touchend",function(){a.Fa.start()});
a.context.j.Ua(a.B,"scroll",a.u4,a);a.context.B.subscribe("onHideControls",function(){a.Pa=!0});
a.context.B.subscribe("onShowControls",function(){a.Pa=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Pa=g.lu(a.J.getRootNode(),"ytp-autohide")});
a.qa.push(g.SE("iv-button-shown",a.v6,a));a.qa.push(g.SE("iv-button-hidden",a.u6,a));a.qa.push(g.SE("iv-teaser-shown",a.F0,a));a.qa.push(g.SE("iv-teaser-hidden",a.w6,a));a.qa.push(g.SE("iv-teaser-clicked",a.E0,a))},njb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.S(b.onClickCommand,g.Keb))?void 0:c.targetId)?(a.va=b,!0):!1},ojb=function(a,b){a.va=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.JPa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.S(h[0],g.pYa))?void 0:d.timeRangeStartMillis)||0,a.va=null,!0}return!1},q4=function(a,b){if(!njb(a,b)||ojb(a,b)){var c=pjb(a,b);
if(c){var d={og:b,jM:c.element,sX:!1};if(!b.onClickCommand){a.isInitialized||mjb(a);jjb(a,b.id);var e=qjb(a,d);g.Pb(a.cards,e,0,d);c.Ga(a.B,e);a.xG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,t4(a),rjb(a,d),o4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&sjb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){sjb(a,d)}),t4(a))}}},pjb=function(a,b){switch(b.type){case "simple":a=a.Ca;
var c=b.displayDomain?{I:"div",T:"iv-card-image-text",Aa:b.displayDomain}:void 0;var d=ajb(b);c={I:"div",Na:["iv-card"],X:[{I:"a",T:"iv-click-target",Y:{href:b.url?g4(b.url)||"":""},X:[j4(b.imageUrl,c),{I:"div",T:"iv-card-content",X:[i4("h2",void 0,b.title),d]}]}]};c=new g.T(c);k4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Ca;c={I:"div",Na:["iv-card","iv-card-channel"],X:[{I:"a",Na:["iv-click-target"],Y:{href:g4(b.url)||"","data-ytid":b.channelId},X:[j4(b.UY),{I:"div",
T:"iv-card-content",X:[Zib(b),{I:"h2",T:"iv-card-primary-link",Aa:b.title},$ib(b)]}]}]};c=new g.T(c);k4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Ca;c={I:"div",Na:["iv-card","iv-card-playlist"],X:[{I:"a",T:"iv-click-target",Y:{href:g4(b.url)||""},X:[j4(b.BF,{I:"div",T:"iv-card-image-overlay",X:[{I:"span",T:"iv-card-playlist-video-count",Aa:b.playlistVideoCount}]}),{I:"div",T:"iv-card-content",X:[Zib(b),i4("h2","iv-card-primary-link",b.title),$ib(b)]}]}]};c=new g.T(c);
k4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Ca;var e=0!=b.offers.length;c=["iv-card"];d="";var f=ajb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",T:"iv-card-offer-price",Aa:f.price}),f.merchant&&e.push({I:"div",T:"iv-card-offer-merchant",Aa:f.merchant}),f={I:"div",X:e});e=b.url?g4(b.url)||"":"";c={I:"div",Na:c,Y:{tabindex:"0"},X:[{I:"a",Na:["iv-card-image","iv-click-target"],Y:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",T:"iv-card-content",X:[b.sponsored?{I:"div",T:"iv-card-sponsored",X:["Sponsored",{I:"div",T:"iv-ad-info-container",X:[{I:"div",T:"iv-ad-info",Aa:"{{adInfo}}"},{I:"div",T:"iv-ad-info-icon-container",X:[{I:"div",T:"iv-ad-info-icon"},{I:"div",T:"iv-ad-info-callout"}]}]}]}:"",{I:"a",T:"iv-click-target",Y:{href:e},X:[i4("h2",d,b.title),f]}]}]};c=new g.T(c);d=g.lf("span");g.Bf(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.oe(d,"adInfo");k4(a,g.Ze("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Ca;d=b.videoDuration?{I:"span",T:"iv-card-video-duration",Aa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Na:["yt-badge","yt-badge-live"],Aa:"LIVE NOW"}:null;e={I:"div",Na:["iv-card","iv-card-video"],X:[{I:"a",T:"iv-click-target",Y:{href:(null==(c=b.url)?void 0:g4(c))||""},X:[j4(b.BF,d),{I:"div",T:"iv-card-content",X:[Zib(b),i4("h2","iv-card-primary-link",b.title),$ib(b),f]}]}]};c=new g.T(e);k4(a,g.Ze("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},qjb=function(a,b){if(0===a.cards.length)return 0;
a=g.Cb(a.cards,function(c){return b.og.startMs>c.og.startMs||b.og.startMs===c.og.startMs&&b.og.timestamp>=c.og.timestamp?!0:!1});
return-1===a?0:a+1},tjb=function(a){if(a.j)return"productListing"===a.j.og.type;
if(a.J.N("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.cq(a.cards,function(c){return"productListing"===c.og.type})}return g.cq(a.cards,function(c){return"productListing"===c.og.type})},t4=function(a){g.qu(a.J.getRootNode(),"ytp-cards-shopping-active",tjb(a))},sjb=function(a,b){if(!g.lu(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.QF(),d=a.j?a.j.og.vg:a.vg;
c&&d&&g.fG(c,[d]);a.j=b;t4(a)}(c=a.isInitialized&&"none"==a.Gb().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.og.teaserDurationMs&&a.J.UA(!0,{teaserText:b.og.teaserText,durationMs:b.og.teaserDurationMs,onClickCommand:b.og.onClickCommand});a.rb.isActive()||((!a.C||!a.Fa.isActive()&&a.Pa)&&rjb(a,b),a.rb.start(910+b.og.teaserDurationMs))}},rjb=function(a,b){a.ea.Ib?(b=new W3([0,
a.B.scrollTop],[0,b.jM.offsetTop],600,yib),a.context.C.Ua(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Ua(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.sG(a.ea,!0),a.B.scrollTop=b.jM.offsetTop,g.sG(a.ea,!1))},u4=function(a){return a.j&&a.j.og?a.j.og:a.cards[0]&&a.cards[0].og?a.cards[0].og:null},ijb=function(a,b){return g.Bb(a.cards,function(c){return c.og.id===b})},v4=function(a,b,c){l4.call(this,a,b);
this.annotation=c;this.isActive=!1},ujb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},w4=function(a,b,c){v4.call(this,a,b,c);
this.B=null;this.S=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},vjb=function(a,b){var c=void 0===c?0:c;
var d=pib(b).width;g.Ir(b,d);c=new wib(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,xib);g.L(a,c);a.context.C.Ua(c,"begin",function(){g.Or(b,!0)});
c.play()},yjb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Na:["iv-branding-context-name"],Aa:b.channel_name}),d=a.createElement({I:"div",Na:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.kW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J),a.j.Ga(d));var f=a.createElement({I:"div",Na:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Na:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Or(h,!1);var l=a.createElement({I:"div",Na:["branding-context-container-outer"]});l.appendChild(h);g.Cr(l,"right",b.image_width+"px");g.nf(a.Gb(),l);a.C=new g.eu(function(){wjb(a,h,l)},500);
g.L(a,a.C);a.context.j.Ua(a.Gb(),"mouseover",function(){xjb(a,h,l,f,b.image_height)});
a.context.j.Ua(a.Gb(),"mouseout",function(){a.C.start()})}},xjb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Nr(b);a.j||(b.style.width=g.Hr(f.width,!0),c.style.width=g.Hr(f.width,!0));g.Cr(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Cr(d,"right","1px");a.D=!0;g.Or(b,!0);a.G=new g.eu(function(){g.mu(this.Gb(),"iv-branding-active")},0,a);
a.G.start()}},wjb=function(a,b,c){g.ou(a.Gb(),"iv-branding-active");
a.K=new g.eu(function(){g.Or(b,!1);a.j||(c.style.width=g.Hr(0,!0))},250);
a.K.start();a.D=!1},zjb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.Z=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Ajb=function(a,b,c){v4.call(this,a,b,c);
var d=this;this.ma=this.isCollapsed=this.ea=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.S=this.createElement({I:"div",Na:["iv-promo-contents"]});this.G=new g.eu(function(){d.j.setAttribute("aria-hidden","true");g.Or(d.C,!1);g.Or(d.B,!0)},700,this);
g.L(this,this.G)},Djb=function(a,b,c){c.stopPropagation();
Bjb(a);Cjb(a,b);a.j.focus()},Ejb=function(a){a.isCollapsed||a.ma||a.D||(g.mu(a.Gb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Bjb=function(a){a.G.stop();
a.isCollapsed&&(g.pu(a.Gb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Or(a.B,!1),g.Or(a.C,!0))},Cjb=function(a,b){a.D||(a.D=g.hg(function(){Fjb(this);
Ejb(this)},b,a))},Fjb=function(a){a.D&&(g.Qa.clearTimeout(a.D),a.D=null)},Gjb=function(a){this.J=a},kjb=function(a,b,c){b&&(c?x4(a,b.map(function(d){return g.Ut(d,c)})):x4(a,b))},x4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.EE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Hjb=function(a){g.yV.call(this,a);
var b=this;this.ea=this.S=!1;this.loadNumber=0;this.K={};this.logger=new Gjb(this.player);this.D=new g.ZK(this);this.G=this.mx=null;this.events=new g.ZK(this);this.wh=this.ma=this.j=null;this.qa=[];g.L(this,this.D);this.D.V(this.player,"onVideoAreaChange",function(){b.ra("onVideoAreaChange")});
this.D.V(this.player,"onHideControls",function(){b.ra("onHideControls")});
this.D.V(this.player,"onShowControls",function(){b.ra("onShowControls")});
this.D.V(this.player,"resize",function(d){b.ra("resize",d)});
this.D.V(this.player,"presentingplayerstatechange",function(d){b.ra("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.G0,this);this.subscribe("resize",this.XI,this);this.player.W().Oa.subscribe("vast_info_card_add",this.AY,this);g.L(this,this.events);this.va=this.createElement({I:"div",T:"video-custom-annotations"});this.B=new g.T({I:"div",Na:["ytp-player-content","ytp-iv-player-content"]});g.L(this,this.B);g.wU(this.player,this.B.element,4);this.B.hide();this.C=new g.T({I:"div",Na:["ytp-iv-video-content"]});g.L(this,this.C);a=this.createElement({I:"div",T:"video-annotations"});
a.appendChild(this.va);this.C.element.appendChild(a);this.ou()&&this.load();var c=this.createElement({I:"style"});(g.Xe("HEAD")[0]||document.body).appendChild(c);g.ub(this,function(){g.yf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Ijb=function(a){a=a.createElement({I:"div",
Na:["annotation","annotation-type-custom"]});g.Or(a,!1);return a},Jjb=function(a,b){b=!b.isCued()&&!g.aH(b,1024);
g.sG(a.B,b);g.sG(a.C,b)},Kjb=function(a,b,c){a.S=!0;
a.G=g.oC(b,c)},Ljb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Xa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Ljb(a,e))}return c},Pjb=function(a){var b=a.player.getVideoData();
if(b.Ya){var c=a.player.W().Oa.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.iC(h)&&h.responseXML?h.responseXML:null)&&Mjb(a,h)}};
g.vD()&&(d.onFinish=Njb(a,d.onFinish));d.postParams={ic_only:"1"};Ojb(d,c);a.S=!0;g.oC(b.Ya,d)}}},Ojb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.CG&&(a.postParams.ic_coll=b.CG);b.kM&&(a.postParams.ic_xml=b.kM);b.mK&&(a.postParams.ic_track=b.mK)},Qjb=function(a){var b=new g.T({I:"div"});
g.Or(b.element,!1);var c=new fjb(a.player,b.element,y4(a));g.L(c,b);b.Ga(a.B.element);c.rF();return c},Sjb=function(a,b){var c,d;
if(b=null==(c=b.Jd)?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.ea=!0,Rjb(a,b),b.headerText&&a.wh&&(c=g.wG(b.headerText),a.wh.setAttribute("title",c))},y4=function(a){if(!a.ma){var b=new zib(a);
g.L(a,b);var c=new g.xo(a);g.L(a,c);a.ma=new zjb(b,c,a.player.W(),a.player.getVideoData(),a.logger,a.player,a.Pi)}return a.ma},Mjb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.QF();if(e){var f=g.PF();f&&g.WB(g.aua)(void 0,e,f,[g.OF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Ljb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=f4(f.type,Tjb),p=f4(f.style,Ujb),q=Pib(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=Vib;if(null==t)var v=null;else if(g.Wa(t)){l=[];for(var x=g.u(t),B=x.next();!B.done;B=x.next()){var G=f(B.value);
G&&l.push(G)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new Wib(m,n,p,v,r):null}else e=null}catch(ra){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=Ijb(f),P=null;switch(l.type){case "branding":if(f.player.W().Vd)break;f.B.element.appendChild(I);P=new w4(I,y4(f),l);break;case "promotion":g.wU(f.player,I,4),P=new Ajb(I,y4(f),l)}P&&P.rF();if(f=P)g.L(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Qjb(a),g.L(a,a.j));if("card"===e.type){c=a.j;var R=e&&e.data&&e.data.card_type;
f=e.data;if(R)switch(l=f.tracking||{},l={JW:l.impression,click:l.click,close:l.close,WZ:l.teaser_impression,iK:l.teaser_click},I=f.tracking_params||{},P=null,R){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:I.card?g.OF(I.card):null,Cl:I.teaser?g.OF(I.teaser):null,vg:I.icon?g.OF(I.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,UY:f.image_url,title:f.title,metaInfo:f.meta_info,url:h4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};q4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:I.card?g.OF(I.card):null,Cl:I.teaser?
g.OF(I.teaser):null,vg:I.icon?g.OF(I.icon):null,BF:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:h4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};q4(c,e);break;case "productListing":f.signin_url&&(P=h4({target:"current",value:f.signin_url}));R=[];for(var Y=f.offers||[],ka=0;ka<Y.length;ka++)R.push(new bjb(g.Be(Y[ka].merchant),g.Be(Y[ka].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:I.card?g.OF(I.card):null,Cl:I.teaser?g.OF(I.teaser):null,vg:I.icon?g.OF(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,qC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:h4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),wgb:P,vgb:f.signin_title?f.signin_title:void 0,ugb:f.signin_message?f.signin_message:void 0,offers:R,onClickCommand:null};q4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:I.card?g.OF(I.card):
null,Cl:I.teaser?g.OF(I.teaser):null,vg:I.icon?g.OF(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,qC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:h4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};q4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,To:I.card?g.OF(I.card):null,Cl:I.teaser?g.OF(I.teaser):null,vg:I.icon?g.OF(I.icon):null,BF:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:h4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},q4(c,e)}}else gjb(a.j,e);c=!0}}c&&
(R3(a.player),a.XI())},Rjb=function(a,b){var c=!1;
a.j||(a.j=Qjb(a),g.L(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(hjb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.LT(f)||(c=a.j,d=b.headerText?g.wG(b.headerText):"",g.Bf(c.Ub,d),c.ma&&c.ma.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ia=b.trackingParams?g.OF(b.trackingParams):null,c.S=b.closeButton.infoCardIconRenderer.trackingParams?g.OF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.vg=b.icon.infoCardIconRenderer.trackingParams?g.OF(b.icon.infoCardIconRenderer.trackingParams):null,a.XI());R3(a.player)}},Vjb=function(a,b,c,d,e){if(!a.player.W().Vd){var f=[];
b.navigationEndpoint&&g.S(b.navigationEndpoint,g.VU)&&g.S(b.navigationEndpoint,g.VU).browseId&&f.push(new Sib("openUrl","click",new Qib("/channel/"+g.S(b.navigationEndpoint,g.VU).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.S(b.subscribeButton,
g.ET)){d.channel_id=g.S(b.subscribeButton,g.ET).channelId;var l;b=g.S(b.subscribeButton,g.ET);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.wG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.wG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.wG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.wG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.S(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.J2))?void 0:m.url)||"";l={subscribeText:g.wG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.wG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Wib(c,"branding","branding",f,d);l=Ijb(a);a.B.element.appendChild(l);f=new w4(l,y4(a),f);f.rF();g.L(f,f);a.K[c]=f}},Njb=function(a,b){return function(){var c=g.Ja.apply(0,arguments);
a.isDisposed()||a.qa.push(g.Xt.Ii(function(){b.apply(null,g.pa(c))}))}},Wjb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.oU.prototype.UA=g.ba(19,function(a,b){var c=g.PV(this.Eb());c&&c.UA(a,b)});
var T3={},U3=null;g.gb(W3,g.Cu);g.k=W3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;V3(this);this.startTime=a=g.eb();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.NI();this.mm("play");this.isPaused()&&this.mm("resume");this.j=1;var b=g.ab(this);b in T3||(T3[b]=this);sib();tib(this,a);return!0};
g.k.stop=function(a){V3(this);this.j=0;a&&(this.progress=1);uib(this,this.progress);this.mm("stop");this.jr()};
g.k.pause=function(){this.isPlaying()&&(V3(this),this.j=-1,this.mm("pause"))};
g.k.Ba=function(){0==this.j||this.stop(!1);this.mm("destroy");W3.Rf.Ba.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.HK=function(){this.mm("animate")};
g.k.mm=function(a){this.dispatchEvent(new vib(a,this))};
g.gb(vib,g.xb);g.gb(X3,W3);X3.prototype.C=function(){};
X3.prototype.HK=function(){this.C();X3.Rf.HK.call(this)};
X3.prototype.jr=function(){this.C();X3.Rf.jr.call(this)};
X3.prototype.NI=function(){this.C();X3.Rf.NI.call(this)};
g.gb(wib,X3);wib.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(zib,g.J);g.k=zib.prototype;g.k.Ua=function(a,b,c,d){c=(0,g.cb)(c,d||this.B);a=g.XC(a,b,c);this.j.push(a);return a};
g.k.lI=function(a,b,c,d){c=(0,g.cb)(c,d||this.B);a=qib(a,b,c);this.j.push(a);return a};
g.k.Qc=function(a){g.YC(a);g.Fb(this.j,a)};
g.k.Of=function(){g.YC(this.j);this.j.length=0};
g.k.Ba=function(){this.Of();g.J.prototype.Ba.call(this)};g.w(Cib,g.yV);g.k=Cib.prototype;g.k.load=function(){g.yV.prototype.load.call(this);if(!$3(this)){var a=g.lRa(this.player.getVideoData());a?(a=Bib(a,Dib(this)),a4(this,a,!1)):Eib(this)}};
g.k.unload=function(){a4(this,null);this.C&&(this.C.abort(),this.C=null);g.yV.prototype.unload.call(this)};
g.k.Jh=function(a,b){return $3(this)?"loadCustomEndscreenRenderer"===a?(a=Bib(b,"new"),a4(this,a),!0):null:null};
g.k.getOptions=function(){return $3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Nb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Xjb.length;f++){var h=Math.abs(b.width-Xjb[f]);if(-1===e||d>=h)e=f,d=h}d=Yjb[e];this.B&&g.Cr(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Mr(e.element,m,f);g.Ir(e.element,n,p);g.pu(e.element,Zjb);256<m||256<f?g.mu(e.element,"ytp-ce-large-round"):96<m||96<f?g.mu(e.element,"ytp-ce-medium-round"):g.mu(e.element,"ytp-ce-small-round");g.pu(e.element,$jb);m=h.left+h.width/2;h=h.top+l/2;g.mu(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.pu(e.element,Yjb);g.mu(e.element,d);(e=g.Ye(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Cr(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())e4(this,this.endscreen.impressionUrls),(a=g.QF())&&this.endscreen.visualElement&&g.dG(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.mu(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.mu(b,"ytp-ce-shown");e4(this,c.impressionUrls);(b=g.QF())&&g.dG(b,c.visualElement);this.player.W().K&&this.player.Ta("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.ou(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.ou(b,"ytp-ce-shown");this.player.W().K&&this.player.Ta("endscreenelementhidden",a)}};
g.k.E9=function(a){var b=this;a.target===window&&(new g.eu(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.pu(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Xjb=[346,426,470,506,570,640,853,1280,1920],Yjb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),$jb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Zjb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Rib={jqa:"current",YPa:"new"};var Tib={CLOSE:"close",zTa:"openUrl",SUBSCRIBE:"subscribe"},Uib={Loa:"click",CLOSE:"close",ABa:"hidden",xYa:"rollOut",yYa:"rollOver",e_a:"shown"};Wib.prototype.jf=function(){var a=Xib(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Ujb={Hja:"anchored",d0:"branding",CHANNEL:"channel",Zpa:"cta",DBa:"highlightText",EFa:"label",PLAYLIST:"playlist",XVa:"popup",b2a:"speech",SUBSCRIBE:"subscribe",p5a:"title",VIDEO:"video",Cbb:"website"},Tjb={d0:"branding",Fma:"card",ksa:"drawer",CBa:"highlight",FLa:"marker",sXa:"promotion",TEXT:"text",cdb:"widget"};g.w(l4,g.J);g.k=l4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.oK(a,b,{id:c,namespace:"annotations_module"});d&&this.eb.set(a,d);e&&this.fb.set(a,e);this.context.J.xf([a])};
g.k.rF=function(){this.context.B.subscribe("resize",this.xG,this)};
g.k.Gb=function(){return this.element};
g.k.IK=function(a,b,c,d,e,f){if(this.xb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.yf(this.Gb())};
g.k.xG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=g4(a);if(f){var h=djb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Td||!1,n=g.bC(f||"");m&&n&&(n.v||n.list)?e.context.J.Bo(n.v,b,n.list,!1):g.uH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);x4(this.context.logger,c,l,d);cjb(f)||(c=g.QF(),d=b.itct,c&&d&&g.gG(c,g.OF(d)))}};
g.k.Ba=function(){this.eb.clear();this.fb.clear();g.J.prototype.Ba.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.L(this,a);return a.element};g.w(fjb,l4);g.k=fjb.prototype;g.k.ut=function(){this.va&&q4(this,this.va)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Nr(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.xG=function(){var a=this.isAvailable();g.Or(this.Gb(),a);g.qu(this.context.J.getRootNode(),g.aZ.IV_DRAWER_ENABLED,a);R3(this.J)};
g.k.destroy=function(){this.J.UA(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.TE(this.qa);g.cD(this.Va);this.Ya&&this.Ya.dispose();this.G&&this.G.dispose();l4.prototype.destroy.call(this)};
g.k.Y3=function(){if(this.C){x4(this.context.logger,u4(this).bj.close);var a=g.QF();a&&this.S&&g.gG(a,this.S);p4(this)}};
g.k.u4=function(){g.qu(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.v6=function(){var a=g.QF(),b=u4(this);b=b?b.vg:this.vg;a&&b&&g.eG(a,[b])};
g.k.u6=function(){var a=g.QF(),b=u4(this);b=b?b.vg:this.vg;a&&b&&g.fG(a,[b])};
g.k.F0=function(){var a=u4(this);x4(this.context.logger,a.bj.WZ);var b=g.QF();b&&a&&g.eG(b,[a.Cl,a.vg])};
g.k.w6=function(){var a=g.QF(),b=u4(this);a&&b&&g.fG(a,[b.Cl])};
g.k.E0=function(a){var b=u4(this),c=g.QF();this.j?a?(a=this.context.logger,x4(a,b.bj.iK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Cl&&g.gG(c,b.Cl)):(a=this.context.logger,x4(a,b.bj.iK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.vg&&g.gG(c,b.vg)):(a=this.context.logger,x4(a,b.bj.iK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.vg&&g.gG(c,this.vg))};g.w(v4,l4);v4.prototype.rF=function(){l4.prototype.rF.call(this);ujb(this)};
v4.prototype.show=function(){l4.prototype.show.call(this);var a=g.QF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.eG(a,[g.OF(b.itct)])};
v4.prototype.hide=function(){l4.prototype.hide.call(this);var a=g.QF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.fG(a,[g.OF(b.itct)])};g.w(w4,v4);w4.prototype.Mw=function(){g.mu(this.Gb(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Na:["branding-img","iv-click-target"],Y:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Or(this.B,!1);var b=this.createElement({I:"button",Na:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Gb().appendChild(b);var c=this.annotation.jf();c&&m4(this,b,c,this.annotation.id,a.session_data);yjb(this,a)};
w4.prototype.show=function(){if(!this.isActive&&(v4.prototype.show.call(this),this.S||(this.Mw(),this.S=!0),g.Or(this.Gb(),!0),this.isActive=!0,this.B)){try{vjb(this,this.B)}catch(a){}g.mu(this.context.J.getRootNode(),"ytp-branding-shown")}};
w4.prototype.hide=function(){this.isActive&&(v4.prototype.hide.call(this),g.Or(this.Gb(),!1),this.isActive=!1,g.ou(this.context.J.getRootNode(),"ytp-branding-shown"))};
w4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);v4.prototype.destroy.call(this)};g.w(Ajb,v4);g.k=Ajb.prototype;
g.k.Mw=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Gb().setAttribute("aria-hidden","true");this.Gb().setAttribute("aria-label","Promotion");this.Gb().tabIndex=0;var e=this.annotation.jf(),f=b.image_url;if(f){var h=this.createElement({I:"div",Na:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
Y:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",T:"iv-promo-video-duration",Aa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",T:"iv-promo-playlist-length",Aa:b.playlist_length.toString()}),h.appendChild(f));e&&m4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",T:"iv-promo-txt"}),g.In(f,g4(e)),this.j=f):this.j=this.createElement({I:"div",T:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",X:[{I:"strong",Aa:b.text_line_1}]});var m=this.createElement({I:"p",X:[{I:"span",T:"iv-promo-link",Aa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Na:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Na:["iv-button","iv-promo-button"],X:[{I:"span",T:"iv-button-content",Aa:f}]});var p=this.createElement({I:"div",T:"iv-promo-button-container"});p.appendChild(f);e&&m4(this,
this.Gb(),e,this.annotation.id,b.session_data,void 0,c)}g.mu(this.j,"iv-click-target");e&&m4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",X:[{I:"span",Aa:b.text_line_1}]}),m=this.createElement({I:"p",X:[{I:"strong",Aa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Na:["yt-badge","iv-promo-badge-live"],Aa:"LIVE NOW"})),g.mu(this.j,"iv-click-target"),e&&m4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.S.appendChild(this.j);p&&this.S.appendChild(p);c=this.createElement({I:"div",T:"iv-promo-actions"});this.B=this.createElement({I:"button",Na:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Ua(this.B,"click",function(q){Djb(a,5E3,q)});
c.appendChild(this.B);g.Or(this.B,!1);this.context.j.Ua(this.Gb(),"mouseover",this.u5,this);this.context.j.Ua(this.Gb(),"mouseout",this.t5,this);this.context.j.Ua(this.Gb(),"touchend",function(q){Djb(a,5E3,q)});
this.C=this.createElement({I:"button",Na:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Ua(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.p5:this.o5,this);c.appendChild(this.C);g.nu(this.Gb(),d);h&&(g.nf(this.Gb(),h),n&&h.appendChild(n));g.nf(this.Gb(),this.S);g.nf(this.Gb(),c)};
g.k.show=function(){this.isActive||(v4.prototype.show.call(this),this.ea||(this.Mw(),this.ea=!0),g.Or(this.Gb(),!0),g.hg(function(){g.ou(this.Gb(),"iv-promo-inactive")},100,this),this.Gb().removeAttribute("aria-hidden"),this.isActive=!0,Fjb(this),Bjb(this),Cjb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.mu(this.Gb(),"iv-promo-inactive"),this.isActive=!1,this.Gb().setAttribute("aria-hidden","true"))};
g.k.IK=function(a,b,c,d,e,f){return this.isCollapsed?!1:v4.prototype.IK.call(this,a,b,c,d,e,f)};
g.k.u5=function(a){this.ma=!0;Djb(this,500,a)};
g.k.t5=function(){this.ma=!1;Ejb(this)};
g.k.o5=function(a){a.stopPropagation();this.hide()};
g.k.p5=function(a){a.stopPropagation();Fjb(this);this.isCollapsed=!0;g.mu(this.Gb(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();v4.prototype.destroy.call(this)};g.w(Hjb,g.yV);g.k=Hjb.prototype;g.k.Jh=function(a,b){if(!Wjb(this.player.W().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.o2(b))&&Mjb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(jjb(this.j,b),R3(this.player)),!0}return null};
g.k.getOptions=function(){return Wjb(this.player.W().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.ou=function(){var a=this.player.W(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.Td&&a.qa||g.iU(this.player.app)?!1:1===c&&!b.kU||a.Oa.get(b.videoId)||g.MT(b)||g.mRa(b)?!0:!1};
g.k.XI=function(){if(this.C){var a=this.player.tb().getVideoContentRect(!0);g.Mr(this.C.element,a.width,a.height);g.Ir(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Rk();a=this.j;b=b.width;g.qu(a.D,"iv-drawer-small",426>=b);g.qu(a.D,"iv-drawer-big",1280<=b)}};
g.k.G0=function(a){Jjb(this,a.state);g.aH(a.state,2)&&(this.Gk()&&this.So()&&2!==this.player.getPresentingPlayerType()&&this.VA(!1),this.UA(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.iC(h)&&h.responseXML?h.responseXML:null)&&(Mjb(b,h),g.mu(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.yV.prototype.load.call(this);Jjb(this,this.player.Tb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.vD()&&(a=Njb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.W().Oa.get(d);f&&Ojb(e,f);f=f&&(f.kM||f.CG);if(!c.wx||f)c.Ya?Kjb(this,c.Ya,e):(this.mx=function(){if(!b.S)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.LT(h))&&!b.ea&&Sjb(b,h)},this.player.addEventListener("videodatachange",this.mx));
g.wU(this.player,this.C.element,4);this.XI();(f=g.MT(c))&&Rjb(this,f);(f=g.mRa(c))&&f.featuredChannel&&Vjb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.wh=g.$e("ytp-cards-button",this.player.getRootNode());g.LT(c)&&Sjb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ya&&Kjb(this,b.Ya,a)};
g.k.unload=function(){this.player.mf("annotations_module");for(var a=g.u(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.ma=null;this.j&&(this.j.destroy(),this.j=null,R3(this.player));this.S=!1;this.G&&(this.G.abort(),this.G=null);this.ea=!1;this.K={};this.B.hide();g.yV.prototype.unload.call(this);this.C.detach();this.mx&&(this.player.removeEventListener("videodatachange",this.mx),this.mx=null)};
g.k.AY=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Pjb(this):this.load())};
g.k.Gk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.ea};
g.k.So=function(){return!!this.j&&this.j.C};
g.k.VA=function(a,b,c){b=void 0===b?!1:b;this.Gk();this.j&&(a?c?o4(this.j,c,b):o4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):p4(this.j))};
g.k.UA=function(a,b){this.player.ra(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.Ba=function(){this.player.W().Oa.unsubscribe("vast_info_card_add",this.AY,this);g.ou(this.player.getRootNode(),g.aZ.IV_DRAWER_OPEN);for(var a=this.qa,b=g.Xt,c=0,d=a.length;c<d;c++)b.Mj(a[c]);this.qa.length=0;g.yV.prototype.Ba.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.L(this,a);return a.element};g.xV("annotations_module",Hjb);g.xV("creatorendscreen",Cib);})(_yt_player);
